platform :ios, '11.4'
use_frameworks!
project 'BaseApp.xcodeproj'
workspace 'BaseApp'

def networkingPods
    pod 'Alamofire'
end

target 'BaseApp' do
  networkingPods
  target 'BaseAppTests' do
  end
end

target 'HomeScreen' do
    project 'HomeScreen/HomeScreen'
    target 'HomeScreenTests' do
    end
end

target 'Extensions' do
    project 'Extensions/Extensions'
    target 'ExtensionsTests' do
    end
end
