#platform :ios, '9.0'

target 'BaseApp' do
  use_frameworks!

  # Pods for BaseApp
    pod 'RxSwift',    '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'
    pod 'Alamofire'

  target 'BaseAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BaseAppUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '~> 4.0'
    pod 'RxTest',     '~> 4.0'
  end

end
